services:
  db:
    image: postgres:16
    container_name: livraria-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: livraria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro

volumes:
  postgres_data:
